In [1]:
import numpy as np

In [2]:
import array

In [3]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [6]:
np.random.rand(3)     # generTes 3 random data            # returns data from 'uniform distribution'

array([0.29892146, 0.3550667 , 0.02202246])

In [8]:
 np.random.randn(5)                          # returns data from 'standard normal distribution'

array([-1.17180763,  0.6627263 , -0.46868186, -0.97602862, -0.03961755])

In [10]:
np.random.randn(3,4)

array([[-0.07748024, -0.76451153,  0.82114036,  0.3815825 ],
       [-1.2307558 , -1.38372464, -0.82963251,  0.6820123 ],
       [ 1.19107889, -0.42728059,  1.57700559, -0.95865926]])

In [14]:
np.random.randn(2,3,4)

array([[[-0.74427203, -1.36922623, -0.50506206, -0.37570267],
        [-0.4712745 , -0.19136402,  1.16655721,  1.24440582],
        [ 0.11836845,  2.83883831, -0.2475187 ,  0.69938928]],

       [[-0.51477655, -2.07068958, -0.34583692,  0.95721001],
        [-1.8948295 , -0.6590565 , -0.35816937, -0.34378761],
        [ 0.2447873 ,  0.38504522,  0.32781053,  0.95717832]]])

In [17]:
np.random.randint(31)       # generates random integers

18

In [18]:
np.random.randint(1,5) 

3

In [20]:
np.random.randint(2,20,(4,4)) # between 2,20 we generated 4 cross 4 matrix

array([[ 4,  3, 15,  5],
       [14,  2, 15,  6],
       [ 9, 19,  9,  7],
       [ 9,  9, 15, 13]])

In [21]:
arr=np.random.randint(6,23,(3,3))

In [22]:
arr

array([[12, 16,  7],
       [21, 10,  6],
       [20, 12, 17]])

In [23]:
arr.reshape(9,1)

array([[12],
       [16],
       [ 7],
       [21],
       [10],
       [ 6],
       [20],
       [12],
       [17]])

In [24]:
arr.reshape(1,9)

array([[12, 16,  7, 21, 10,  6, 20, 12, 17]])

In [28]:
#lets reshape it in 3 d

In [29]:
arr.reshape(1,1,9)

array([[[12, 16,  7, 21, 10,  6, 20, 12, 17]]])

In [31]:
arr.reshape(3,3,1)

array([[[12],
        [16],
        [ 7]],

       [[21],
        [10],
        [ 6]],

       [[20],
        [12],
        [17]]])

In [40]:
arr.max()

21

In [41]:
arr.min()

6

In [43]:
arr[2: ,2:]

array([[17]])

In [44]:
arr[:,[0,1]]

array([[12, 16],
       [21, 10],
       [20, 12]])

In [45]:
arr>10

array([[ True,  True, False],
       [ True, False, False],
       [ True,  True,  True]])

In [46]:
arr[arr>10]

array([12, 16, 21, 20, 12, 17])

In [47]:
arr

array([[12, 16,  7],
       [21, 10,  6],
       [20, 12, 17]])

In [48]:
arr*arr

array([[144, 256,  49],
       [441, 100,  36],
       [400, 144, 289]])

In [50]:
arr1=np.random.randint(6,90,(3,3))

# 

In [51]:
arr1*arr

array([[1368, 4674, 1656],
       [1168, 3741,  798],
       [3871, 2788, 3588]])

In [52]:
arr1@arr         #matrix multiplication

array([[ 8131, 10506,  6915],
       [ 9238,  9194,  5277],
       [ 9144, 11695,  6486]])

In [53]:
arr/0

C:\Users\Snehja Srivastava\AppData\Local\Temp\ipykernel_18352\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [54]:
arr**2                       # array to the power 2

array([[5776, 3249,  576],
       [ 256, 7569,  441],
       [6241, 1156, 4761]])

In [55]:
# BROADCASTING CONCEPT

In [56]:
arr=np.zeros((3,4))

In [57]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
a= np.array([1,3,4,6])

In [60]:
arr+a

array([[1., 3., 4., 6.],
       [1., 3., 4., 6.],
       [1., 3., 4., 6.]])

In [61]:
arr+5         # it broadcasts 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [68]:
b=np.array([5,6,4])

In [69]:
b+arr

ValueError: operands could not be broadcast together with shapes (3,) (3,4) 

In [70]:
b.reshape(3,1)

array([[5],
       [6],
       [4]])

In [72]:
b.reshape(3,1)+arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [4., 4., 4., 4.]])

In [73]:
# ANOTHER WAY

In [74]:
b.T

array([5, 6, 4])

In [75]:
# covert in 2 d tabhi axis define hogi

In [76]:
b=np.array([[5,6,4]])

In [77]:
b.T

array([[5],
       [6],
       [4]])

In [78]:
b.T+arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [4., 4., 4., 4.]])

In [79]:
# lets find square root

In [85]:
arr1=np.random.rand(3,4)

In [86]:
arr1

array([[0.73657029, 0.39440362, 0.21308056, 0.92874634],
       [0.20138169, 0.72280303, 0.28684124, 0.87131311],
       [0.71824653, 0.71583215, 0.71249002, 0.13735752]])

In [89]:
np.sqrt(arr1)

array([[0.85823673, 0.62801562, 0.4616065 , 0.96371487],
       [0.44875571, 0.85017823, 0.53557561, 0.93344154],
       [0.84749426, 0.84606865, 0.84409124, 0.37061775]])

In [93]:
np.log10(arr1)

array([[-0.1327858 , -0.40405911, -0.67145617, -0.03210288],
       [-0.69598002, -0.14098003, -0.54235841, -0.05982575],
       [-0.14372647, -0.1451888 , -0.14722122, -0.86214757]])

In [97]:
np.random.seed(13)      # this prevents random data to change when we run

In [103]:
np.random.seed(13)
np.random.rand(2,3)

array([[0.77770241, 0.23754122, 0.82427853],
       [0.9657492 , 0.97260111, 0.45344925]])