In [1]:
import numpy as np

In [2]:
import array

In [9]:
np.fromiter(range(5) , dtype=int)

array([0, 1, 2, 3, 4])

In [11]:
np.fromstring('23,45,346,45,7' , sep= ',' , dtype=int)

array([ 23,  45, 346,  45,   7])

In [17]:
np.fromstring("23 35 45 6 65" , sep=' ' , dtype=complex)        # string 

array([23.+0.j, 35.+0.j, 45.+0.j,  6.+0.j, 65.+0.j])

In [19]:
l= [1,22,43,534,64,575,68]                # passing list in array
np.array(l)

array([  1,  22,  43, 534,  64, 575,  68])

In [33]:
l=[[2,3,5,5] , [3,5,465,4] , [4,4,67,9]]


In [34]:
np.array(l)


array([[  2,   3,   5,   5],
       [  3,   5, 465,   4],
       [  4,   4,  67,   9]])

In [35]:
arr1=np.array(l)

In [36]:
arr1.ndim

2

In [37]:
arr1.size # gives size of elements

12

In [38]:
arr1.shape # rows,column

(3, 4)

In [39]:
arr2=np.array([[[2,3,5,5] , [3,5,465,4] , [4,4,67,9]]])

In [40]:
arr2

array([[[  2,   3,   5,   5],
        [  3,   5, 465,   4],
        [  4,   4,  67,   9]]])

In [42]:
arr2.shape

(1, 3, 4)