In [1]:
import numpy as np

In [2]:
import array

In [4]:
#creating array


In [10]:
np.array([1,2,3,4,5,'madhusudan','6+2i'])             # note the brackets

array(['1', '2', '3', '4', '5', 'madhusudan', '6+2i'], dtype='<U11')

In [9]:
type(np.array([1,2,3,4,5])   )

numpy.ndarray

In [12]:
np.array([[3,4],[6,7]])

array([[3, 4],
       [6, 7]])

In [13]:
np.array([[3,4],[6,7],[6,8]])

array([[3, 4],
       [6, 7],
       [6, 8]])

In [14]:
np.array([[3,4],[6,7],[6,7,8]])          # we get a warning that uniform data not there so it accepts as list

C:\Users\Snehja Srivastava\AppData\Local\Temp\ipykernel_23756\208804455.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[3,4],[6,7],[6,7,8]])


array([list([3, 4]), list([6, 7]), list([6, 7, 8])], dtype=object)

In [15]:
# [--------one D array
#   [[-------two D array
#      [[[-------3D array............ and so on..................

In [16]:
#ndmin gives dimensions
np.array([1,2,3],ndmin=3)

array([[[1, 2, 3]]])

In [17]:
# TYPE CONVERSION


In [20]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [21]:
# HOW TO PLOT 1 D DATA

In [22]:
np.array([(1,3),(4,7)])

array([[1, 3],
       [4, 7]])